// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKnowledgeDir(arg1, arg2) {
  return window['go']['app']['App']['CreateKnowledgeDir'](arg1, arg2);
}

export function DeleteKnowledgeFile(arg1, arg2) {
  return window['go']['app']['App']['DeleteKnowledgeFile'](arg1, arg2);
}

export function EnsureKnowledgeDirs(arg1) {
  return window['go']['app']['App']['EnsureKnowledgeDirs'](arg1);
}

export function ExportFile(arg1, arg2) {
  return window['go']['app']['App']['ExportFile'](arg1, arg2);
}

export function FetchLocalSkills(arg1) {
  return window['go']['app']['App']['FetchLocalSkills'](arg1);
}

export function FetchMarketPlugins() {
  return window['go']['app']['App']['FetchMarketPlugins']();
}

export function FetchMcpMarket(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchMcpMarket'](arg1, arg2, arg3);
}

export function FetchMcpMarketWithCookies(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['FetchMcpMarketWithCookies'](arg1, arg2, arg3, arg4, arg5);
}

export function FetchSkillCollectionInfo(arg1) {
  return window['go']['app']['App']['FetchSkillCollectionInfo'](arg1);
}

export function FetchSkillFileContent(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['FetchSkillFileContent'](arg1, arg2, arg3, arg4);
}

export function FetchSkillFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['FetchSkillFiles'](arg1, arg2, arg3, arg4);
}

export function FetchSkillReadme(arg1, arg2) {
  return window['go']['app']['App']['FetchSkillReadme'](arg1, arg2);
}

export function FetchSkillsMarket(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchSkillsMarket'](arg1, arg2, arg3);
}

export function ImportFile() {
  return window['go']['app']['App']['ImportFile']();
}

export function InstallAuiPlugin(arg1, arg2, arg3) {
  return window['go']['app']['App']['InstallAuiPlugin'](arg1, arg2, arg3);
}

export function ListAuiOutputDir(arg1, arg2) {
  return window['go']['app']['App']['ListAuiOutputDir'](arg1, arg2);
}

export function ListAuiPlugins(arg1) {
  return window['go']['app']['App']['ListAuiPlugins'](arg1);
}

export function ListKnowledgeFiles(arg1, arg2) {
  return window['go']['app']['App']['ListKnowledgeFiles'](arg1, arg2);
}

export function LoadAuiPlugin(arg1, arg2) {
  return window['go']['app']['App']['LoadAuiPlugin'](arg1, arg2);
}

export function OpenProjectDirectory(arg1) {
  return window['go']['app']['App']['OpenProjectDirectory'](arg1);
}

export function PtyResize(arg1, arg2, arg3) {
  return window['go']['app']['App']['PtyResize'](arg1, arg2, arg3);
}

export function PtyStart(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PtyStart'](arg1, arg2, arg3, arg4);
}

export function PtyStop(arg1) {
  return window['go']['app']['App']['PtyStop'](arg1);
}

export function PtyWrite(arg1, arg2) {
  return window['go']['app']['App']['PtyWrite'](arg1, arg2);
}

export function ReadAuiOutputFile(arg1, arg2) {
  return window['go']['app']['App']['ReadAuiOutputFile'](arg1, arg2);
}

export function ReadKnowledgeFile(arg1, arg2) {
  return window['go']['app']['App']['ReadKnowledgeFile'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function StarMe() {
  return window['go']['app']['App']['StarMe']();
}

export function UninstallAuiPlugin(arg1, arg2) {
  return window['go']['app']['App']['UninstallAuiPlugin'](arg1, arg2);
}

export function WriteKnowledgeFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteKnowledgeFile'](arg1, arg2, arg3);
}
