// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateKnowledgeDir(arg1:string,arg2:string):Promise<void>;

export function DeleteKnowledgeFile(arg1:string,arg2:string):Promise<void>;

export function EnsureKnowledgeDirs(arg1:string):Promise<void>;

export function ExportFile(arg1:string,arg2:string):Promise<string>;

export function FetchMarketPlugins():Promise<Array<app.MarketPlugin>>;

export function ImportFile():Promise<string>;

export function InstallAuiPlugin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAuiPlugins(arg1:string):Promise<Array<app.AuiPluginMeta>>;

export function ListKnowledgeFiles(arg1:string,arg2:string):Promise<Array<app.FileInfo>>;

export function LoadAuiPlugin(arg1:string,arg2:string):Promise<app.AuiPluginAssets>;

export function PtyResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PtyStart(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PtyStop(arg1:string):Promise<void>;

export function PtyWrite(arg1:string,arg2:string):Promise<void>;

export function ReadKnowledgeFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StarMe():Promise<app.StarResult>;

export function UninstallAuiPlugin(arg1:string,arg2:string):Promise<void>;

export function WriteKnowledgeFile(arg1:string,arg2:string,arg3:string):Promise<void>;
