// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKnowledgeDir(arg1, arg2) {
  return window['go']['app']['App']['CreateKnowledgeDir'](arg1, arg2);
}

export function DeleteKnowledgeFile(arg1, arg2) {
  return window['go']['app']['App']['DeleteKnowledgeFile'](arg1, arg2);
}

export function EnsureKnowledgeDirs(arg1) {
  return window['go']['app']['App']['EnsureKnowledgeDirs'](arg1);
}

export function ExportFile(arg1, arg2) {
  return window['go']['app']['App']['ExportFile'](arg1, arg2);
}

export function FetchMarketPlugins() {
  return window['go']['app']['App']['FetchMarketPlugins']();
}

export function ImportFile() {
  return window['go']['app']['App']['ImportFile']();
}

export function InstallAuiPlugin(arg1, arg2, arg3) {
  return window['go']['app']['App']['InstallAuiPlugin'](arg1, arg2, arg3);
}

export function ListAuiPlugins(arg1) {
  return window['go']['app']['App']['ListAuiPlugins'](arg1);
}

export function ListKnowledgeFiles(arg1, arg2) {
  return window['go']['app']['App']['ListKnowledgeFiles'](arg1, arg2);
}

export function LoadAuiPlugin(arg1, arg2) {
  return window['go']['app']['App']['LoadAuiPlugin'](arg1, arg2);
}

export function PtyResize(arg1, arg2, arg3) {
  return window['go']['app']['App']['PtyResize'](arg1, arg2, arg3);
}

export function PtyStart(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PtyStart'](arg1, arg2, arg3, arg4);
}

export function PtyStop(arg1) {
  return window['go']['app']['App']['PtyStop'](arg1);
}

export function PtyWrite(arg1, arg2) {
  return window['go']['app']['App']['PtyWrite'](arg1, arg2);
}

export function ReadKnowledgeFile(arg1, arg2) {
  return window['go']['app']['App']['ReadKnowledgeFile'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function StarMe() {
  return window['go']['app']['App']['StarMe']();
}

export function UninstallAuiPlugin(arg1, arg2) {
  return window['go']['app']['App']['UninstallAuiPlugin'](arg1, arg2);
}

export function WriteKnowledgeFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteKnowledgeFile'](arg1, arg2, arg3);
}
