// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateKnowledgeDir(arg1:string,arg2:string):Promise<void>;

export function DeleteKnowledgeFile(arg1:string,arg2:string):Promise<void>;

export function EnsureKnowledgeDirs(arg1:string):Promise<void>;

export function ExportFile(arg1:string,arg2:string):Promise<string>;

export function FetchLocalSkills(arg1:string):Promise<Array<app.LocalSkillInfo>>;

export function FetchMarketPlugins():Promise<Array<app.MarketPlugin>>;

export function FetchMcpMarket(arg1:number,arg2:number,arg3:string):Promise<string>;

export function FetchMcpMarketWithCookies(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function FetchSkillCollectionInfo(arg1:string):Promise<string>;

export function FetchSkillFileContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function FetchSkillFiles(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function FetchSkillReadme(arg1:string,arg2:string):Promise<string>;

export function FetchSkillsMarket(arg1:number,arg2:number,arg3:string):Promise<string>;

export function ImportFile():Promise<string>;

export function InstallAuiPlugin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAuiOutputDir(arg1:string,arg2:string):Promise<Array<app.AuiOutputFileInfo>>;

export function ListAuiPlugins(arg1:string):Promise<Array<app.AuiPluginMeta>>;

export function ListKnowledgeFiles(arg1:string,arg2:string):Promise<Array<app.FileInfo>>;

export function LoadAuiPlugin(arg1:string,arg2:string):Promise<app.AuiPluginAssets>;

export function OpenProjectDirectory(arg1:string):Promise<void>;

export function PtyResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PtyStart(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PtyStop(arg1:string):Promise<void>;

export function PtyWrite(arg1:string,arg2:string):Promise<void>;

export function ReadAuiOutputFile(arg1:string,arg2:string):Promise<app.AuiOutputFileResult>;

export function ReadKnowledgeFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StarMe():Promise<app.StarResult>;

export function UninstallAuiPlugin(arg1:string,arg2:string):Promise<void>;

export function WriteKnowledgeFile(arg1:string,arg2:string,arg3:string):Promise<void>;
