// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKnowledgeDir(arg1, arg2) {
  return window['go']['main']['App']['CreateKnowledgeDir'](arg1, arg2);
}

export function DeleteKnowledgeFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteKnowledgeFile'](arg1, arg2);
}

export function EnsureKnowledgeDirs(arg1) {
  return window['go']['main']['App']['EnsureKnowledgeDirs'](arg1);
}

export function ListKnowledgeFiles(arg1, arg2) {
  return window['go']['main']['App']['ListKnowledgeFiles'](arg1, arg2);
}

export function ReadKnowledgeFile(arg1, arg2) {
  return window['go']['main']['App']['ReadKnowledgeFile'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StarMe() {
  return window['go']['main']['App']['StarMe']();
}

export function WriteKnowledgeFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteKnowledgeFile'](arg1, arg2, arg3);
}
