// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hello():Promise<boolean>;

export function StarMe():Promise<main.StarResult>;

export namespace main {
  export class StarResult {
    message: string;
    count: number;
  }
}
