// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hello() {
  return window['go']['main']['App']['Hello']();
}

export function StarMe() {
  return window['go']['main']['App']['StarMe']();
}

export function StarMeReturnType() {
  return window['go']['main']['App']['StarMeReturnType']();
}
