// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteKnowledgeFile(arg1:string,arg2:string):Promise<void>;

export function EnsureKnowledgeDirs(arg1:string):Promise<Array<main.KnowledgeDir>>;

export function ListKnowledgeFiles(arg1:string,arg2:string):Promise<Array<main.FileInfo>>;

export function ReadKnowledgeFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StarMe():Promise<main.StarResult>;

export function WriteKnowledgeFile(arg1:string,arg2:string,arg3:string):Promise<void>;
