// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateKnowledgeDir(arg1:string,arg2:string):Promise<void>;

export function DeleteKnowledgeFile(arg1:string,arg2:string):Promise<void>;

export function EnsureKnowledgeDirs(arg1:string):Promise<void>;

export function ExportFile(arg1:string,arg2:string):Promise<string>;

export function ImportFile():Promise<string>;

export function ListKnowledgeFiles(arg1:string,arg2:string):Promise<Array<main.FileInfo>>;

export function PtyResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PtyStart(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function PtyStop(arg1:string):Promise<void>;

export function PtyWrite(arg1:string,arg2:string):Promise<void>;

export function ReadKnowledgeFile(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function StarMe():Promise<main.StarResult>;

export function WriteKnowledgeFile(arg1:string,arg2:string,arg3:string):Promise<void>;
